### ISSUE TITLE
ASCII verification issue

### ISSUE THREAD

**Issue by crisdut** [strict-types/strict-types#19]
I started the rgb-contracts crate update and found a bug in issuing a new contract:

```
thread 'main' panicked at 'global type doesn't match type definition: TypeMismatch { value: String("TST"), expected: List(SemId(Array<32>(6015c0e70764a9f48ae71dd448caf4035bffebdb62eff70dc8794286f8910f41)), Sizing { min: 1, max: 8 }) }', src/bin/rgb/command.rs:445:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I ended up realizing that at [this stage,](https://github.com/strict-types/strict-types/blob/master/src/value/typify.rs#L223-L226), the  `id.is_ascii_char()` return false instead of true.

If we change the verification to check string is ascii, this works!

```rust
(StrictVal::String(s), Ty::List(id, _)) if s.is_ascii() => {
     AsciiString::from_ascii(s.as_bytes()).map_err(|err| err.ascii_error())?;
     StrictVal::String(s)
}
```

I used the version https://github.com/strict-types/strict-types/commit/65202d1dfc142af26ef5aaaba8efd5d4ffd360cc

Also, see bellow the yaml used in rgb-contracts:

```yaml
interface: RGB20

globals:
  spec:
    naming:
      ticker: TST
      name: TST
      details: ~
    precision: 2
  terms: >
    TST.
assignments:
  beneficiary:
    seal: tapret1st:5ad5255a9958e8f9932f431756f326207ab46bdaba76f2740a8e290601b3fb47:0
    amount: 5

```

Thanks

**Comment by dr-orlovsky** [comment]
I see... The actual fix has to be much more complex and I am working on it.

The problem is the fact that now we have different forms of strings with restricted character sets, and ASCII is just one of them (others are like "alphanumeric", different use of caps etc). Thus, we have to handle all those cases now.

**Comment by dr-orlovsky** [comment]
I tried all possible ways to fix the issue without breaking changes; however it was impossible. The actual fix requires to allow using lists of enums as keys in map types (map keys had to be a primitive types or byte strings).

PRs fixing the issue:
* https://github.com/strict-types/strict-encoding/pull/21
* https://github.com/strict-types/strict-types/pull/20

**Comment by crisdut** [comment]
> I tried all possible ways to fix the issue without breaking changes; however it was impossible. The actual fix requires to allow using lists of enums as keys in map types (map keys had to be a primitive types or byte strings).
> 
> PRs fixing the issue:
> 
> * [Remove register_ascii API strict-encoding#21](https://github.com/strict-types/strict-encoding/pull/21)
> * [Refactor Map key type system #20](https://github.com/strict-types/strict-types/pull/20)

Sure, I will test it ASAP.

**Comment by dr-orlovsky** [comment]
@crisdut please use

```toml
[patch.crates-io]
strict_encoding = { git = "https://github.com/strict-types/strict-encoding", branch = "ascii-char" }
strict_types = { git = "https://github.com/strict-types/strict-types", branch = "restricted-keys" }
rgb-core = { git = "https://github.com/RGB-WG/rgb-core", branch = "develop" }
rgb-std = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "develop" }
rgb-wallet = { git = "https://github.com/RGB-WG/rgb-wallet", branch = "develop" }
```

and the updated master tip of `rgb-contract`.

It is working for all my tests. Waiting for your confirmation to release
