### ISSUE TITLE
Make ordering of StrictValue fields relaxed

### ISSUE THREAD

**Issue by zoedberg** [strict-types/strict-types#7]
I'm trying to issue an RGB20 asset but encountering this error:

```
thread 'main' panicked at 'bug in business logic of type system. Details:
Union(
    Ord(
        0,
    ),
    Unit,
)
Tuple(
    UnnamedFields(
        Confined(
            [
                SemId(
                    Array<32>(5cd0c3c0db677e225d50c0cd55a38fd2a79d3a29d625e34f78dfd6166c3cb806),
                ),
            ],
        ),
    ),
)', /home/zoe/.cargo/registry/src/github.com-1ecc6299db9ec823/strict_types-1.0.0/src/value/encode.rs:180:23

```

As reported by the logs, the error comes from [here](https://github.com/strict-types/strict-types/blob/v1.0.0/src/value/encode.rs#L180). In rgb CLI the error comes from [strict_serialize_type call](https://github.com/RGB-WG/rgb/blob/master/src/bin/rgb/command.rs#L425).

I've managed to find the cause of the error, which is inverting order of `Nominal` keys in yaml file, for example:
```
globals:
  Nominal:
    details: ~
    name: USD Tether
    precision: 0
    ticker: USDT
```
doesn't work (throws the reported error) while this:
```
globals:
  Nominal:
    ticker: USDT
    name: USD Tether
    details: ~
    precision: 0
```
works. @dr-orlovsky I don't know how to fix the issue but I hope I provided enough info to address it.
